owner: GrattaWebDesignStudio
repo: upptime # The name of this repository

sites:
  - name: mmrma
    url: https://mmrma.org/
  - name: boundaryelectric
    url: https://www.boundaryelectric.com/
  - name: ethicsinsight
    url: https://ethicsinsight.co/
  - name: vanyoo
    url: https://www.vanyoo.com/
  - name: micheauxfilmfest
    url: https://micheauxfilmfest.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime 
  logoUrl: https://avatars.githubusercontent.com/u/40851165
  name: Upptime
  introTitle: "**Gratta Studio** – WordPress & WooCommerce Development Experts"
  introMessage: "We’re a dedicated WordPress Development Agency creating bespoke, high-performance websites and eCommerce solutions"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
